### ISSUE TITLE
Deploy and Compute

### ISSUE THREAD

**Issue by YangXiaoXiong** [alien4cloud/docker-tosca-types#1]
I want to use TOSCA to manage my kubernetes and mesos.
Alien4cloud just has its own implementation of the TOSCA protocol.
Alien4cloud is using Cloudify to control kubernetes.
I tested the implementation of the Cloudify submitting task to kubernetes, but when I tried to use Alien4cloud to submit this Topology, there was a problem with the deployment.
I have to set up Location, since I have no cloud environment (IAAS), And I already have kubernetes cluster and Cloudfiy, so I chose BYON as Location.
BYON needs to be provided the host pool address, so I built a host pool service, while the final deployment has been stuck in the initialization process.
Here is what I do not understand: kubernetes has already have the resources, we only need to submit the task to Cloudfiy, Cloudfiy then submit to the kubernetes deployment, why I have to set up Location, and also we need to use the machine inside the host pool?

**Comment by lucboutier** [comment]
Hi,

First of all I am not clear on what you tries to achieve ? We believe that Kubernetes and Mesos are container management systems and actually support these platforms for Docker deployment use-cases. In theses use-case we don't support Docker as a VM but as an immutable image-based element.

We don't support deployment of tosca.nodes.Compute nodes for theses platform as it seems that docker may not be the best type of containers for VM kind of deployments. We may rather leverage LXC containers for theses kind of usages.

There are discutions on support of LXC containers in Kubernetes or Marathon but this is not yet a reality:
https://github.com/kubernetes/kubernetes/issues/6862
https://github.com/lxc/lxd/issues/670
 
If you don't need to deploy Compute nodes but only Docker nodes then you can use our Marathon or Cfy/Kubernetes implementation (any location no specific on-demand resource configuration). If you wish to deploy Hybrid Topologies with Docker and Compute nodes then while the Docker part will be managed by Kubernetes we will delegate to another VM or Physical machine management the Compute part (based on the configured location).

If what you really need is Docker as a VM (as you understood we don't believe that this is the best technology for this use-case) there is two options:
 -use docker on the same machine where the alien is you can use the puccini orchestrator (see our getting started). This can also we used with swarm with additional configuration
 - Or you will have to create a Kubernetes location for the cloudify plugin that maps the tosca.nodes.Compute node to Kubernetes nodes.

HTH,

Luc

**Comment by YangXiaoXiong** [comment]
I am very excited to see your reply, thank you very much to give me an answer
My English is poor and I may not be very clear about what I mean. I combine pictures to explain what I want to do

I have kubernetes clusters, and Cloudify now .They are all installed on my 5 VM

![1](https://user-images.githubusercontent.com/27332805/28161852-ab48350c-67f7-11e7-8cc3-0621ec00e21b.png)

I mean that, kubernetes cluster has managed some resources, there are 3 node

![2](https://user-images.githubusercontent.com/27332805/28161905-e3c8da12-67f7-11e7-9996-a3358708c6ee.png)

Eventually, I want to deploy a mongodb instance of docker through alien4cloud


![3](https://user-images.githubusercontent.com/27332805/28161924-f4f1f616-67f7-11e7-91f3-579fa3296fad.png)

I think that as long as we put the Tosca description of the Topology sent to Cloudify, will be able to complete the deployment of Cloudify will be a service deployment by kubernetes URL,
kubernetes has its own resources, so we do not have to worry about where he will make the deployment of mongodb （he will deployment on his nodes）
When we build the plug-in, we also specify the corresponding address, and I think it's enough

![4](https://user-images.githubusercontent.com/27332805/28161934-fab983b6-67f7-11e7-8c9b-27b47600d5da.png)


So I don't understand the role of our set location, why do we need machines inside the mainframe pool?.


In addition, when I was deployed according to the document, I saw that Alien4cloud had already submitted the task to Cloudify, but the task on Cloudify could not be deployed successfully, and I would continue to study it.
